#!/bin/bash

#color are mentioned
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

#this is update code
apt update  && apt upgrade -y
#remove "#" from below line to enable full-upgrade

#apt-get full-upgrade -y
stat=$?




#update sucess or not

if [ $stat -eq 2 ];then
echo -e "\n\n ${RED} error on execution ${NC}"
exit

elif [ $stat -eq 0 ];then
echo -e "\n\n ${GREEN} Updated Sucessfully ${NC}"
fi

#removing  temp
apt autoremove -y >/dev/null 
apt-get autoclean -y >/dev/null 

